#!/usr/bin/env node
// Generate docs/TOOLS.md from what an agent actually sees.
//
// The contracts are read back through document.modelContext.getTools() on the
// live page rather than from our source, so the documentation cannot drift away
// from the registration. If a description changes, this file changes with it.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import { chromium } from 'playwright';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const target = process.argv[2];

let server = null;
let base = target;
if (!base) {
  server = spawn('npx', ['--yes', 'serve', 'web', '-l', '4174', '--no-clipboard'], { stdio: 'ignore', cwd: ROOT });
  base = 'http://localhost:4174';
  await new Promise((r) => setTimeout(r, 2500));
}

const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto(base, { waitUntil: 'networkidle' });
await page.waitForFunction(async () => (await document.modelContext?.getTools?.())?.length > 0, null, { timeout: 15000 });

const tools = await page.evaluate(async () => {
  const list = await document.modelContext.getTools();
  return list.map((t) => ({
    name: t.name,
    title: t.title || t.name,
    description: t.description,
    inputSchema: typeof t.inputSchema === 'string' ? t.inputSchema : JSON.stringify(t.inputSchema ?? {}),
    annotations: t.annotations ?? null,
  }));
});

await browser.close();
server?.kill();

const order = ['zipcheckup_lookup_zip', 'zipcheckup_compare_zips', 'zipcheckup_explain_metric', 'zipcheckup_find_safer_zips', 'zipcheckup_update_shortlist', 'zipcheckup_draft_civic_letter'];
tools.sort((a, b) => order.indexOf(a.name) - order.indexOf(b.name));

const lines = [
  '# Tool contracts',
  '',
  `Generated by \`npm run build:docs\` from \`document.modelContext.getTools()\` on the running page, so these are the contracts an agent actually receives, not a hand-maintained copy of them.`,
  '',
  `${tools.length} tools registered.`,
  '',
  '| Tool | Kind |',
  '|---|---|',
  ...tools.map((t) => `| [\`${t.name}\`](#${t.name.replace(/_/g, '')}) | ${t.annotations?.readOnlyHint ? 'read-only' : '**writes to page state**'} |`),
  '',
];

for (const t of tools) {
  const schema = JSON.parse(t.inputSchema);
  lines.push(
    `## \`${t.name}\``,
    '',
    `**${t.title}**`,
    '',
    t.description,
    '',
    `\`annotations\`: \`readOnlyHint: ${t.annotations?.readOnlyHint}\`, \`untrustedContentHint: ${t.annotations?.untrustedContentHint}\``,
    '',
    '```json',
    JSON.stringify(schema, null, 2),
    '```',
    '',
  );
}

lines.push(
  '## The value envelope',
  '',
  'Every metric crosses the tool boundary as an object, never as a bare number.',
  '',
  '```jsonc',
  `{ "metric": "lead_level_mg_l", "status": "known", "value": 0, "unit": "mg/L",`,
  `  "qualifier": "reported_as_zero_non_detect",`,
  `  "qualifier_note": "A reported 0 means the result was below the laboratory detection limit. It is not a measurement of \\"no lead\\".",`,
  `  "source": { "dataset": "...", "upstream": "...", "license": "CC-BY-4.0" },`,
  `  "measured": { "as_of": "2026-08-19", "precision": "dataset_snapshot_date" },`,
  `  "threshold": { "name": "EPA lead action level", "value": 0.015, "unit": "mg/L",`,
  `                 "citation": "40 CFR Part 141 Subpart I", "comparison": "at_or_below" } }`,
  '```',
  '',
  'and for a value the source does not have:',
  '',
  '```jsonc',
  `{ "metric": "boil_water_advisories", "status": "unknown", "value": null,`,
  `  "unknown_reason": "this column is present in the source schema but empty for all 42,679 rows",`,
  `  "not_a_claim_of": "zero, none, clean, safe, or that the metric was measured and came back negative",`,
  `  "how_to_resolve": "Ask the water system or the state drinking-water primacy agency" }`,
  '```',
  '',
  'Every result also carries a `data_quality` block with known/unknown counts and an `agent_instructions` string that tells the model, in its own payload, not to render an unknown as 0, "none", "clean" or "safe".',
  '',
);

mkdirSync(join(ROOT, 'docs'), { recursive: true });
writeFileSync(join(ROOT, 'docs', 'TOOLS.md'), `${lines.join('\n')}`);
process.stderr.write(`docs/TOOLS.md written from ${tools.length} live registrations\n`);
